package application

import (
	"context"

	"github.com/SongYii/open-code-harness/internal/harness/domain"
	"github.com/SongYii/open-code-harness/internal/harness/engine"
)

// RunTurnRequest starts one model-backed assistant Turn in an active Session.
// Command identity is generated by Application and is correlation lineage, not
// a caller-visible idempotency key.
type RunTurnRequest struct {
	SessionID domain.SessionID
	Input     string
	Sink      engine.RuntimeSink
}

// RunTurnResult describes the durable boundary known to this invocation.
// Records contains defensive copies of every batch accepted for this call.
type RunTurnResult struct {
	SessionID         domain.SessionID
	TurnID            domain.TurnID
	ItemID            domain.ItemID
	Status            domain.TurnStatus
	Text              string
	TerminalCommitted bool
	DeliveryWarning   error
	Records           []domain.RecordedEvent
}

// RunTurn is the sole application authority for one durable model Turn. It
// performs every reversible check before atomic admission and never retries a
// Store append or model call.
func (service *Service) RunTurn(ctx context.Context, request RunTurnRequest) (RunTurnResult, error) {
	if service == nil || !validRunTurnRequest(request) {
		return RunTurnResult{}, applicationError(CategoryValidation, "invalid_request", false, nil)
	}
	if err := contextError(ctx); err != nil {
		return RunTurnResult{}, err
	}

	records, err := service.store.Load(ctx, request.SessionID)
	if !isNilValue(err) {
		return RunTurnResult{}, mapLoadError(ctx, err)
	}
	if err := contextError(ctx); err != nil {
		return RunTurnResult{}, err
	}
	if len(records) == 0 {
		return RunTurnResult{}, applicationError(CategoryValidation, "session_not_found", false, nil)
	}
	state, err := domain.Replay(records)
	if err != nil || state.ID != request.SessionID {
		return RunTurnResult{}, applicationError(CategoryInternal, "store_contract_violation", false, err)
	}
	if err := domain.CheckStartAssistantTurnEligibility(state); err != nil {
		return RunTurnResult{}, applicationError(CategoryValidation, "domain_rejected", false, err)
	}

	turnID, sourceErr := service.ids.NewTurnID()
	if mapped := generatedIDError(ctx, sourceErr); mapped != nil {
		return RunTurnResult{}, mapped
	}
	if _, err := domain.ParseTurnID(string(turnID)); err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "id_generator_contract_violation", false, err)
	}
	itemID, sourceErr := service.ids.NewItemID()
	if mapped := generatedIDError(ctx, sourceErr); mapped != nil {
		return RunTurnResult{}, mapped
	}
	if _, err := domain.ParseItemID(string(itemID)); err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "id_generator_contract_violation", false, err)
	}
	commandID, sourceErr := service.ids.NewCommandID()
	if mapped := generatedIDError(ctx, sourceErr); mapped != nil {
		return RunTurnResult{}, mapped
	}
	if _, err := domain.ParseCommandID(string(commandID)); err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "id_generator_contract_violation", false, err)
	}

	emitter, err := engine.NewEmitter(request.Sink, engine.Correlation{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		CommandID: commandID,
	})
	if err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "emitter_construction_failed", false, err)
	}
	decided, err := domain.Decide(state, domain.StartAssistantTurn{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		Input:     request.Input,
	})
	if err != nil {
		return RunTurnResult{}, applicationError(CategoryValidation, "domain_rejected", false, err)
	}
	runningState, admissionRecords, err := service.appendAndApply(ctx, request.SessionID, state, decided, commandID)
	if err != nil {
		return RunTurnResult{}, err
	}
	runningResult := RunTurnResult{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		Status:    domain.TurnStatusRunning,
		Records:   admissionRecords,
	}

	runResult, err := service.runner.Run(ctx, engine.RunRequest{
		ModelRequest: engine.ModelRequest{
			SessionID: request.SessionID,
			TurnID:    turnID,
			ItemID:    itemID,
			Input:     request.Input,
		},
		MaxAssistantBytes: service.config.MaxAssistantBytes,
	}, emitter)
	if err != nil {
		return cloneRunTurnResult(runningResult), mapRunError(err)
	}

	decided, err = domain.Decide(runningState, domain.CompleteAssistantTurn{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		Text:      runResult.Text,
	})
	if err != nil {
		return cloneRunTurnResult(runningResult), applicationError(CategoryInternal, "domain_transition_failed", false, err)
	}
	_, terminalRecords, err := service.appendAndApply(ctx, request.SessionID, runningState, decided, commandID)
	if err != nil {
		return cloneRunTurnResult(runningResult), err
	}
	completedResult := RunTurnResult{
		SessionID:         request.SessionID,
		TurnID:            turnID,
		ItemID:            itemID,
		Status:            domain.TurnStatusCompleted,
		Text:              runResult.Text,
		TerminalCommitted: true,
		Records:           concatenateRunTurnRecords(admissionRecords, terminalRecords),
	}
	if err := emitter.Emit(ctx, engine.RuntimePayload{Type: engine.RuntimeAppendCompleted}); err != nil {
		return runTurnDeliveryFailure(completedResult, err)
	}
	if err := emitter.Emit(ctx, engine.RuntimePayload{Type: engine.RuntimeModelStreamCompleted}); err != nil {
		return runTurnDeliveryFailure(completedResult, err)
	}
	return cloneRunTurnResult(completedResult), nil
}

func validRunTurnRequest(request RunTurnRequest) bool {
	if _, err := domain.ParseSessionID(string(request.SessionID)); err != nil {
		return false
	}
	return validRequiredText(request.Input) && !isNilValue(request.Sink)
}

func mapRunError(cause error) error {
	switch {
	case engine.IsCode(cause, engine.CodeCanceled):
		return applicationError(CategoryCanceled, "canceled", false, cause)
	case engine.IsCode(cause, engine.CodeOutputLimit):
		return applicationError(CategoryOutputLimit, string(engine.CodeOutputLimit), false, cause)
	case engine.IsCode(cause, engine.CodeDelivery):
		return applicationError(CategoryDelivery, "runtime_delivery_failed", false, cause)
	case engine.IsCode(cause, engine.CodeInvalidRequest):
		return applicationError(CategoryInternal, "engine_contract_violation", false, cause)
	default:
		return applicationError(CategoryModel, runErrorCode(cause), false, cause)
	}
}

func runErrorCode(cause error) string {
	for _, code := range []engine.ErrorCode{
		engine.CodeModelStartup,
		engine.CodeModelStream,
		engine.CodeInvalidStream,
	} {
		if engine.IsCode(cause, code) {
			return string(code)
		}
	}
	return "model_failure"
}

func runTurnDeliveryFailure(result RunTurnResult, cause error) (RunTurnResult, error) {
	warning := cause
	if engineError, ok := cause.(*engine.Error); ok && engineError != nil && engineError.Cause != nil {
		warning = engineError.Cause
	}
	result.DeliveryWarning = warning
	return cloneRunTurnResult(result), applicationError(CategoryDelivery, "runtime_delivery_failed", true, warning)
}

func concatenateRunTurnRecords(batches ...[]domain.RecordedEvent) []domain.RecordedEvent {
	count := 0
	for _, batch := range batches {
		count += len(batch)
	}
	combined := make([]domain.RecordedEvent, 0, count)
	for _, batch := range batches {
		combined = append(combined, batch...)
	}
	return combined
}

func cloneRunTurnResult(result RunTurnResult) RunTurnResult {
	clone := result
	if records, err := domain.CloneRecordedEvents(result.Records); err == nil {
		clone.Records = records
	} else {
		clone.Records = nil
	}
	return clone
}
