package application

import (
	"context"
	"errors"

	"github.com/SongYii/open-code-harness/internal/harness/domain"
	"github.com/SongYii/open-code-harness/internal/harness/engine"
)

// RunTurnRequest starts one model-backed assistant Turn in an active Session.
// Command identity is generated by Application and is correlation lineage, not
// a caller-visible idempotency key.
type RunTurnRequest struct {
	SessionID domain.SessionID
	Input     string
	Sink      engine.RuntimeSink
}

// RunTurnResult describes the durable boundary known to this invocation.
// Records contains defensive copies of every batch accepted for this call.
type RunTurnResult struct {
	SessionID         domain.SessionID
	TurnID            domain.TurnID
	ItemID            domain.ItemID
	Status            domain.TurnStatus
	Text              string
	TerminalCommitted bool
	DeliveryWarning   error
	Records           []domain.RecordedEvent
}

// RunTurn is the sole application authority for one durable model Turn. It
// performs every reversible check before atomic admission and never retries a
// Store append or model call.
func (service *Service) RunTurn(ctx context.Context, request RunTurnRequest) (RunTurnResult, error) {
	if service == nil || !validRunTurnRequest(request) {
		return RunTurnResult{}, applicationError(CategoryValidation, "invalid_request", false, nil)
	}
	if err := contextError(ctx); err != nil {
		return RunTurnResult{}, err
	}

	records, err := service.store.Load(ctx, request.SessionID)
	if !isNilValue(err) {
		return RunTurnResult{}, mapLoadError(ctx, err)
	}
	if err := contextError(ctx); err != nil {
		return RunTurnResult{}, err
	}
	if len(records) == 0 {
		return RunTurnResult{}, applicationError(CategoryValidation, "session_not_found", false, nil)
	}
	state, err := domain.Replay(records)
	if err != nil || state.ID != request.SessionID {
		return RunTurnResult{}, applicationError(CategoryInternal, "store_contract_violation", false, err)
	}
	if err := domain.CheckStartAssistantTurnEligibility(state); err != nil {
		return RunTurnResult{}, applicationError(CategoryValidation, "domain_rejected", false, err)
	}

	turnID, sourceErr := service.ids.NewTurnID()
	if mapped := generatedIDError(ctx, sourceErr); mapped != nil {
		return RunTurnResult{}, mapped
	}
	if _, err := domain.ParseTurnID(string(turnID)); err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "id_generator_contract_violation", false, err)
	}
	itemID, sourceErr := service.ids.NewItemID()
	if mapped := generatedIDError(ctx, sourceErr); mapped != nil {
		return RunTurnResult{}, mapped
	}
	if _, err := domain.ParseItemID(string(itemID)); err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "id_generator_contract_violation", false, err)
	}
	commandID, sourceErr := service.ids.NewCommandID()
	if mapped := generatedIDError(ctx, sourceErr); mapped != nil {
		return RunTurnResult{}, mapped
	}
	if _, err := domain.ParseCommandID(string(commandID)); err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "id_generator_contract_violation", false, err)
	}

	emitter, err := engine.NewEmitter(request.Sink, engine.Correlation{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		CommandID: commandID,
	})
	if err != nil {
		return RunTurnResult{}, applicationError(CategoryInternal, "emitter_construction_failed", false, err)
	}
	decided, err := domain.Decide(state, domain.StartAssistantTurn{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		Input:     request.Input,
	})
	if err != nil {
		return RunTurnResult{}, applicationError(CategoryValidation, "domain_rejected", false, err)
	}
	runningState, admissionRecords, err := service.appendAndApply(ctx, request.SessionID, state, decided, commandID)
	if err != nil {
		return RunTurnResult{}, err
	}
	runningResult := RunTurnResult{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		Status:    domain.TurnStatusRunning,
		Records:   admissionRecords,
	}

	runResult, err := service.runner.Run(ctx, engine.RunRequest{
		ModelRequest: engine.ModelRequest{
			SessionID: request.SessionID,
			TurnID:    turnID,
			ItemID:    itemID,
			Input:     request.Input,
		},
		MaxAssistantBytes: service.config.MaxAssistantBytes,
	}, emitter)
	if err != nil {
		cleanupBase := context.WithoutCancel(ctx)
		cleanupCtx, cancel := context.WithTimeout(cleanupBase, service.config.TerminalCommitTimeout)
		defer cancel()
		return service.terminalizeExecutionFailure(cleanupCtx, ctx, runningState, runningResult, commandID, emitter, err)
	}

	decided, err = domain.Decide(runningState, domain.CompleteAssistantTurn{
		SessionID: request.SessionID,
		TurnID:    turnID,
		ItemID:    itemID,
		Text:      runResult.Text,
	})
	if err != nil {
		return cloneRunTurnResult(runningResult), applicationError(CategoryInternal, "domain_transition_failed", false, err)
	}
	_, terminalRecords, err := service.appendAndApply(ctx, request.SessionID, runningState, decided, commandID)
	if err != nil {
		if ctx.Err() != nil {
			cleanupBase := context.WithoutCancel(ctx)
			cleanupCtx, cancel := context.WithTimeout(cleanupBase, service.config.TerminalCommitTimeout)
			defer cancel()
			primary := applicationError(CategoryCanceled, "canceled", false, errors.Join(ctx.Err(), err))
			return service.terminalizeExecutionFailure(cleanupCtx, ctx, runningState, runningResult, commandID, emitter, primary)
		}
		return cloneRunTurnResult(runningResult), err
	}
	completedResult := RunTurnResult{
		SessionID:         request.SessionID,
		TurnID:            turnID,
		ItemID:            itemID,
		Status:            domain.TurnStatusCompleted,
		Text:              runResult.Text,
		TerminalCommitted: true,
		Records:           concatenateRunTurnRecords(admissionRecords, terminalRecords),
	}
	if err := emitter.Emit(ctx, engine.RuntimePayload{Type: engine.RuntimeAppendCompleted}); err != nil {
		return runTurnDeliveryFailure(completedResult, err)
	}
	if err := emitter.Emit(ctx, engine.RuntimePayload{Type: engine.RuntimeModelStreamCompleted}); err != nil {
		return runTurnDeliveryFailure(completedResult, err)
	}
	return cloneRunTurnResult(completedResult), nil
}

func (service *Service) terminalizeExecutionFailure(
	cleanupCtx context.Context,
	deliveryCtx context.Context,
	runningState domain.Session,
	runningResult RunTurnResult,
	commandID domain.CommandID,
	emitter *engine.Emitter,
	executionCause error,
) (RunTurnResult, error) {
	primary := mapExecutionError(executionCause)
	terminalCommand, status, terminalSignal, stableCode := terminalCommandForExecution(
		runningResult,
		primary,
	)
	decided, err := domain.Decide(runningState, terminalCommand)
	if err != nil {
		return cloneRunTurnResult(runningResult), applicationError(
			CategoryInternal,
			"domain_transition_failed",
			false,
			errors.Join(executionCause, err),
		)
	}
	_, terminalRecords, err := service.appendAndApply(
		cleanupCtx,
		runningResult.SessionID,
		runningState,
		decided,
		commandID,
	)
	if err != nil {
		return cloneRunTurnResult(runningResult), terminalizationError(err, executionCause)
	}

	terminalResult := runningResult
	terminalResult.Status = status
	terminalResult.Text = ""
	terminalResult.TerminalCommitted = true
	terminalResult.Records = concatenateRunTurnRecords(runningResult.Records, terminalRecords)

	committedError := applicationError(primary.Category, primary.Code, true, executionCause)
	if err := emitter.Emit(deliveryCtx, engine.RuntimePayload{Type: engine.RuntimeAppendCompleted}); err != nil {
		return terminalExecutionDeliveryFailure(terminalResult, committedError, err)
	}
	if err := emitter.Emit(deliveryCtx, engine.RuntimePayload{Type: terminalSignal, Code: stableCode}); err != nil {
		return terminalExecutionDeliveryFailure(terminalResult, committedError, err)
	}
	return cloneRunTurnResult(terminalResult), committedError
}

func mapExecutionError(cause error) *Error {
	var existing *Error
	if errors.As(cause, &existing) && existing != nil {
		return existing
	}
	mapped, _ := mapRunError(cause).(*Error)
	return mapped
}

func terminalCommandForExecution(result RunTurnResult, primary *Error) (domain.Command, domain.TurnStatus, engine.RuntimeEventType, string) {
	if primary.Category == CategoryCanceled {
		return domain.InterruptAssistantTurn{
			SessionID: result.SessionID,
			TurnID:    result.TurnID,
			ItemID:    result.ItemID,
			Code:      domain.InterruptionCallerCanceled,
			Message:   "",
		}, domain.TurnStatusInterrupted, engine.RuntimeModelStreamInterrupted, domain.InterruptionCallerCanceled
	}
	if primary.Category == CategoryDelivery {
		return domain.InterruptAssistantTurn{
			SessionID: result.SessionID,
			TurnID:    result.TurnID,
			ItemID:    result.ItemID,
			Code:      domain.InterruptionDeliveryFailed,
			Message:   "",
		}, domain.TurnStatusInterrupted, engine.RuntimeModelStreamInterrupted, domain.InterruptionDeliveryFailed
	}
	code, message := durableFailure(primary)
	return domain.FailAssistantTurn{
		SessionID: result.SessionID,
		TurnID:    result.TurnID,
		ItemID:    result.ItemID,
		Code:      code,
		Message:   message,
	}, domain.TurnStatusFailed, engine.RuntimeModelStreamFailed, code
}

func durableFailure(primary *Error) (string, string) {
	switch primary.Code {
	case string(engine.CodeModelStartup):
		return string(engine.CodeModelStartup), "model failed before streaming"
	case string(engine.CodeModelStream):
		return string(engine.CodeModelStream), "model stream failed"
	case string(engine.CodeOutputLimit):
		return string(engine.CodeOutputLimit), "assistant output exceeded limit"
	case string(engine.CodeInvalidStream):
		return string(engine.CodeInvalidStream), "model stream violated contract"
	default:
		return "model_failure", "model failed"
	}
}

func terminalizationError(terminalCause error, executionCause error) error {
	var terminal *Error
	if errors.As(terminalCause, &terminal) && terminal != nil {
		return applicationError(terminal.Category, terminal.Code, false, errors.Join(executionCause, terminalCause))
	}
	return applicationError(CategoryInternal, "terminalization_failed", false, errors.Join(executionCause, terminalCause))
}

func terminalExecutionDeliveryFailure(result RunTurnResult, primary *Error, cause error) (RunTurnResult, error) {
	warning := runtimeDeliveryCause(cause)
	result.DeliveryWarning = warning
	return cloneRunTurnResult(result), applicationError(
		primary.Category,
		primary.Code,
		true,
		errors.Join(primary.Cause, warning),
	)
}

func validRunTurnRequest(request RunTurnRequest) bool {
	if _, err := domain.ParseSessionID(string(request.SessionID)); err != nil {
		return false
	}
	return validRequiredText(request.Input) && !isNilValue(request.Sink)
}

func mapRunError(cause error) error {
	switch {
	case engine.IsCode(cause, engine.CodeCanceled):
		return applicationError(CategoryCanceled, "canceled", false, cause)
	case engine.IsCode(cause, engine.CodeOutputLimit):
		return applicationError(CategoryOutputLimit, string(engine.CodeOutputLimit), false, cause)
	case engine.IsCode(cause, engine.CodeDelivery):
		return applicationError(CategoryDelivery, "runtime_delivery_failed", false, cause)
	case engine.IsCode(cause, engine.CodeInvalidRequest):
		return applicationError(CategoryInternal, "engine_contract_violation", false, cause)
	default:
		return applicationError(CategoryModel, runErrorCode(cause), false, cause)
	}
}

func runErrorCode(cause error) string {
	for _, code := range []engine.ErrorCode{
		engine.CodeModelStartup,
		engine.CodeModelStream,
		engine.CodeInvalidStream,
	} {
		if engine.IsCode(cause, code) {
			return string(code)
		}
	}
	return "model_failure"
}

func runTurnDeliveryFailure(result RunTurnResult, cause error) (RunTurnResult, error) {
	warning := runtimeDeliveryCause(cause)
	result.DeliveryWarning = warning
	return cloneRunTurnResult(result), applicationError(CategoryDelivery, "runtime_delivery_failed", true, warning)
}

func runtimeDeliveryCause(cause error) error {
	var engineError *engine.Error
	if errors.As(cause, &engineError) && engineError != nil && engineError.Cause != nil {
		return engineError.Cause
	}
	return cause
}

func concatenateRunTurnRecords(batches ...[]domain.RecordedEvent) []domain.RecordedEvent {
	count := 0
	for _, batch := range batches {
		count += len(batch)
	}
	combined := make([]domain.RecordedEvent, 0, count)
	for _, batch := range batches {
		combined = append(combined, batch...)
	}
	return combined
}

func cloneRunTurnResult(result RunTurnResult) RunTurnResult {
	clone := result
	if records, err := domain.CloneRecordedEvents(result.Records); err == nil {
		clone.Records = records
	} else {
		clone.Records = nil
	}
	return clone
}
